version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Mapeia o código-fonte local para o diretório /app no contêiner.
      # Isso permite o hot-reload (graças à flag --reload no Dockerfile)
      # e também persiste o banco de dados 'escola.db' na sua máquina local.
      - .:/app